version: '3.4'

networks:
  shorturl:
    external: false

services:
  db:
    image: redis:6.2.6
    container_name: shorturl_db
    networks:
      - shorturl
    volumes:
      - ./db/redis:/data
  api:
    image: lucasfusinato/shorturl-api
    container_name: shorturl_api
    build:
      context: .
      dockerfile: api/Dockerfile
    networks:
      - shorturl
    environment:
      - DATABASE_TYPE=redis
      - DATABASE_HOST=db
      - DATABASE_PORT=6379
    ports:
      - "8000:8000"
    depends_on:
      - db
  web:
    image: lucasfusinato/shorturl-web
    container_name: shorturl_web
    build:
      context: .
      dockerfile: web/Dockerfile
    networks:
      - shorturl
    environment:
      - PUBLIC_URL=http://localhost:8501
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api