apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: shorturl
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: lucasfusinato/shorturl-api
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "50m"
            memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: shorturl
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30020