apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: lucasfusinato/fusishort-api
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_TYPE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-type
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-host
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-port
        resources:
          limits:
            cpu: "50m"
            memory: "100Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            httpHeaders:
            - name: Accept
              value: application/json
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30020
